<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Entities\Towers\" />
    <Folder Include="Entities\Enemies\" />
    <Folder Include="Systems\" />
    <Folder Include="Map\" />
    <Folder Include="Managers\" />
    <Folder Include="Core\" />
  </ItemGroup>

</Project>
